sudo: false

language: node_js

node_js:
  - "stable"
  - "4"

cache:
  directories:
    - node_modules

script:
  - npm run lint && (if [[ "$TRAVIS_JOB_NUMBER" == *.2 ]]; then npm run cover:lcov; else npm run testonly; fi)

after_failure:
  - (cd resources; python travis_after_all.py)

after_success:
  - (cd resources; python travis_after_all.py)
  - export $(cat resources/.to_export_back)
  - if [[ "$TRAVIS_JOB_NUMBER" == *.1 ]]; then cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi
