sudo: false

language: node_js

node_js:
  - "7"
  - "6"
  - "5"
  - "4"
  - "iojs"
  - "0.12"

cache:
  directories:
    - node_modules

script:
  - if [[ "$TRAVIS_JOB_NUMBER" == *.1 ]]; then npm run lint && npm run check && npm run cover:lcov; else npm run testonly; fi

after_failure:
  - (cd resources; python travis_after_all.py)

after_success:
  - (cd resources; python travis_after_all.py)
  - export $(cat resources/.to_export_back)
  - if [[ "$TRAVIS_JOB_NUMBER" == *.1 ]]; then cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi
